<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $permissions = [
            'Student Information' => [
                'Student' => ['view', 'add', 'edit', 'delete'],
                'Student Admission' => ['view', 'add', 'edit', 'delete'],
                'Bulk Delete' => ['view'],
                'Import Student' => ['view'],
                'Student Categories' => ['view', 'add', 'edit', 'delete'],
                'Student Houses' => ['view', 'add', 'edit', 'delete'],
                'Disable Student' => ['view'],
                'Student Timeline' => ['view', 'add', 'edit', 'delete'],
                'Disable Reason' => ['view', 'add', 'edit', 'delete'],
            ],
            'Fees Collection' => [
                'Collect Fees' => ['view', 'add', 'delete'],
                'Fees Carry Forward' => ['view'],
                'Fees Master' => ['view', 'add', 'edit', 'delete'],
                'Fees Group' => ['view', 'add', 'edit', 'delete'],
                'Fees Group Assign' => ['view'],
                'Fees Type' => ['view', 'add', 'edit', 'delete'],
                'Fees Discount' => ['view', 'add', 'edit', 'delete'],
                'Fees Discount Assign' => ['view'],
                'Search Fees Payment' => ['view'],
                'Search Due Fees' => ['view'],
                'Fees Reminder' => ['view', 'edit'],
                'Offline Bank Payments' => ['view'],
                'Online Bank Payments' => ['view'],
            ],
            'Income' => [
                'Income' => ['view', 'add', 'edit', 'delete'],
                'Income Head' => ['view', 'add', 'edit', 'delete'],
                'Search Income' => ['view'],
            ],
            'Expense' => [
                'Expense' => ['view', 'add', 'edit', 'delete'],
                'Expense Head' => ['view', 'add', 'edit', 'delete'],
                'Search Expense' => ['view'],
            ],
            'Student Attendance' => [
                'Student / Period Attendance' => ['view', 'add', 'edit'],
                'Attendance By Date' => ['view'],
                'Approve Leave' => ['view', 'add', 'edit', 'delete'],
            ],
            'Examination' => [
                'Marks Grade' => ['view', 'add', 'edit', 'delete'],
                'Exam Group' => ['view', 'add', 'edit', 'delete'],
                'Design Admit Card' => ['view', 'add', 'edit', 'delete'],
                'Print Admit Card' => ['view'],
                'Design Marksheet' => ['view', 'add', 'edit', 'delete'],
                'Print Marksheet' => ['view'],
                'Exam Result' => ['view'],
                'Marks Import' => ['view'],
                'Exam' => ['view', 'add', 'edit', 'delete'],
                'Exam Publish' => ['view'],
                'Link Exam' => ['view', 'edit'],
                'Assign / View student' => ['view', 'edit'],
                'Exam Subject' => ['view', 'edit'],
                'Exam Marks' => ['view', 'edit'],
                'Marks Division' => ['view', 'add', 'edit', 'delete'],
                'Exam Schedule' => ['view'],
                'Generate Rank' => ['view'],
            ],
            'Academics' => [
                'Class Timetable' => ['view', 'add', 'edit'],
                'Subject' => ['view', 'add', 'edit', 'delete'],
                'Class' => ['view', 'add', 'edit', 'delete'],
                'Section' => ['view', 'add', 'edit', 'delete'],
                'Promote Student' => ['view'],
                'Assign Class Teacher' => ['view', 'add', 'edit', 'delete'],
                'Teachers Timetable' => ['view'],
                'Subject Group' => ['view', 'add', 'edit', 'delete'],
            ],
            'Download Center' => [
                'Upload Content' => ['view', 'add', 'delete'],
                'Content Type' => ['view', 'add', 'edit', 'delete'],
                'Content Share List' => ['view', 'delete'],
                'Video Tutorial' => ['view', 'add', 'edit', 'delete'],
            ],
            'Library' => [
                'Books List' => ['view', 'add', 'edit', 'delete'],
                'Issue Return' => ['view'],
                'Add Staff Member' => ['view'],
                'Add Student' => ['view'],
                'Import Book' => ['view'],
            ],
            'Inventory' => [
                'Issue Item' => ['view', 'add', 'edit', 'delete'],
                'Add Item Stock' => ['view', 'add', 'edit', 'delete'],
                'Add Item' => ['view', 'add', 'edit', 'delete'],
                'Item Store' => ['view', 'add', 'edit', 'delete'],
                'Item Supplier' => ['view', 'add', 'edit', 'delete'],
                'Item Category' => ['view', 'add', 'edit', 'delete'],
            ],
            'Transport' => [
                'Routes' => ['view', 'add', 'edit', 'delete'],
                'Vehicle' => ['view', 'add', 'edit', 'delete'],
                'Assign Vehicle' => ['view', 'add', 'edit', 'delete'],
                'Pickup Point' => ['view', 'add', 'edit', 'delete'],
                'Route Pickup Point' => ['view', 'add', 'edit', 'delete'],
                'Student Transport Fees' => ['view', 'add', 'edit'],
                'Fees Master' => ['view', 'add', 'edit', 'delete'],
            ],
            'Hostel' => [
                'Hostel' => ['view', 'add', 'edit', 'delete'],
                'Room Type' => ['view', 'add', 'edit', 'delete'],
                'Hostel Rooms' => ['view', 'add', 'edit', 'delete'],
            ],
            'Communicate' => [
                'Notice Board' => ['view', 'add', 'edit', 'delete'],
                'Send Notification' => ['view', 'add', 'edit', 'delete'],
                'Email' => ['view'],
                'Email / SMS Log' => ['view'],
                'SMS' => ['view'],
                'Schedule Email SMS Log' => ['view', 'edit', 'delete'],
                'Login Credentials Send' => ['view'],
                'Notification Template' => ['view', 'add', 'edit', 'delete'],
                'Email Template' => ['view', 'add', 'edit', 'delete'],
                'SMS Template' => ['view', 'add', 'edit', 'delete'],
                'Send WA' => ['view'],
                'WA Template' => ['view', 'add', 'edit', 'delete'],
            ],
            'Reports' => [
                'Student Report' => ['view'],
                'Guardian Report' => ['view'],
                'Student History' => ['view'],
                'Student Login Credential Report' => ['view'],
                'Class Subject Report' => ['view'],
                'Admission Report' => ['view'],
                'Sibling Report' => ['view'],
                'Homework Evaluation Report' => ['view'],
                'Student Profile' => ['view'],
                'Fees Statement' => ['view'],
                'Balance Fees Report' => ['view'],
                'Fees Collection Report' => ['view'],
                'Online Fees Collection Report' => ['view'],
                'Income Report' => ['view'],
                'Expense Report' => ['view'],
                'PayRoll Report' => ['view'],
                'Income Group Report' => ['view'],
                'Expense Group Report' => ['view'],
                'Attendance Report' => ['view'],
                'Staff Attendance Report' => ['view'],
                'Transport Report' => ['view'],
                'Hostel Report' => ['view'],
                'Audit Trail Report' => ['view'],
                'User Log' => ['view'],
                'Book Issue Report' => ['view'],
                'Book Due Report' => ['view'],
                'Book Inventory Report' => ['view'],
                'Stock Report' => ['view'],
                'Add Item Report' => ['view'],
                'Issue Item Report' => ['view'],
                'Student Attendance Type Report' => ['view'],
                'Online Exam Wise Report' => ['view'],
                'Online Exams Report' => ['view'],
                'Online Exams Attempt Report' => ['view'],
                'Online Exams Rank Report' => ['view'],
                'Staff Report' => ['view'],
                'Student / Period Attendance Report' => ['view'],
                'Biometric Attendance Log' => ['view'],
                'Book Issue Return Report' => ['view'],
                'Rank Report' => ['view'],
                'Syllabus Status Report' => ['view'],
                'Subject Lesson Plan Report' => ['view'],
                'Alumni Report' => ['view'],
                'Student Gender Ratio Report' => ['view'],
                'Student Teacher Ratio Report' => ['view'],
                'Daily Attendance Report' => ['view'],
                'Balance Fees Report With Remark' => ['view'],
                'Balance Fees Statement' => ['view'],
                'Daily Collection Report' => ['view'],
                'Online Admission Report' => ['view'],
                'Income Expense Balance Report' => ['view'],
                'Due Fees Report' => ['view'],
                'Homework Marks Report' => ['view'],
                'Online Admission Fees Collection Report' => ['view'],
                'Class Section Report' => ['view'],
                'Leave Request Report' => ['view'],
                'My Leave Request Report' => ['view'],
            ],
            'System Settings' => [
                'Languages' => ['view', 'add', 'edit'],
                'General Setting' => ['view', 'edit'],
                'Session Setting' => ['view', 'add', 'edit', 'delete'],
                'Notification Setting' => ['view', 'edit'],
                'SMS Setting' => ['view', 'edit'],
                'Email Setting' => ['view', 'edit'],
                'Front CMS Setting' => ['view', 'edit'],
                'Payment Methods' => ['view', 'edit'],
                'User Status' => ['view'],
                'Backup' => ['view', 'add', 'delete'],
                'Restore' => ['view'],
                'Language Switcher' => ['view'],
                'Custom Fields' => ['view'],
                'System Fields' => ['view'],
                'Print Header Footer' => ['view'],
                'Student Profile Update' => ['view'],
                'Sidebar Menu' => ['view'],
                'Currency' => ['view'],
                'Currency Switcher' => ['view'],
            ],
            'Front CMS' => [
                'Menus' => ['view', 'add', 'edit', 'delete'],
                'Media Manager' => ['view', 'add', 'edit', 'delete'],
                'Banner Images' => ['view', 'add', 'edit', 'delete'],
                'Pages' => ['view', 'add', 'edit', 'delete'],
                'Gallery' => ['view', 'add', 'edit', 'delete'],
                'Event' => ['view', 'add', 'edit', 'delete'],
                'News' => ['view', 'add', 'edit', 'delete'],
            ],
            'Front Office' => [
                'Admission Enquiry' => ['view', 'add', 'edit', 'delete'],
                'Follow Up Admission Enquiry' => ['view', 'add', 'edit', 'delete'],
                'Visitor Book' => ['view', 'add', 'edit', 'delete'],
                'Phone Call Log' => ['view', 'add', 'edit', 'delete'],
                'Postal Dispatch' => ['view', 'add', 'edit', 'delete'],
                'Postal Receive' => ['view', 'add', 'edit', 'delete'],
                'Complain' => ['view', 'add', 'edit', 'delete'],
                'Setup Front Office' => ['view', 'add', 'edit', 'delete'],
            ],
            'Human Resource' => [
                'Staff' => ['view', 'add', 'edit', 'delete'],
                'Disable Staff' => ['view'],
                'Staff Attendance' => ['view', 'add', 'edit'],
                'Staff Payroll' => ['view', 'add', 'edit', 'delete'],
                'Approve Leave Request' => ['view', 'add', 'edit', 'delete'],
                'Apply Leave' => ['view', 'add', 'edit', 'delete'],
                'Leave Types' => ['view', 'add', 'edit', 'delete'],
                'Department' => ['view', 'add', 'edit', 'delete'],
                'Designation' => ['view', 'add', 'edit', 'delete'],
                'Can See Other Users Profile' => ['view'],
                'Staff Timeline' => ['view', 'add', 'edit', 'delete'],
                'Teachers Rating' => ['view', 'add', 'edit', 'delete'],
            ],
            'Homework' => [
                'Homework' => ['view', 'add', 'edit', 'delete'],
                'Homework Evaluation' => ['view', 'add'],
                'Daily Assignment' => ['view'],
            ],
            'Certificate' => [
                'Student Certificate' => ['view', 'add', 'edit', 'delete'],
                'Generate Certificate' => ['view'],
                'Student ID Card' => ['view', 'add', 'edit', 'delete'],
                'Generate ID Card' => ['view'],
                'Staff ID Card' => ['view', 'add', 'edit', 'delete'],
                'Generate Staff ID Card' => ['view'],
                'Download Transfer Certificate' => ['view'],
                'Build Transfer Certificate' => ['view'],
                'Transfer Certificate Settings' => ['view'],
                'Verify Transfer Certificate' => ['view'],
            ],
            'Calendar To Do List' => [
                'Calendar To Do List' => ['view', 'add', 'edit', 'delete'],
            ],
            'Dashboard and Widgets' => [
                'Quick Session Change' => ['view'],
                'Fees Collection And Expense Monthly Chart' => ['view'],
                'Fees Collection And Expense Yearly Chart' => ['view'],
                'Monthly Fees Collection Widget' => ['view'],
                'Monthly Expense Widget' => ['view'],
                'Student Count Widget' => ['view'],
                'Staff Role Count Widget' => ['view'],
                'Fees Awaiting Payment Widgets' => ['view'],
                'Converted Leads Widgets' => ['view'],
                'Fees Overview Widgets' => ['view'],
                'Enquiry Overview Widgets' => ['view'],
                'Library Overview Widgets' => ['view'],
                'Student Today Attendance Widgets' => ['view'],
                'Income Donut Graph' => ['view'],
                'Expense Donut Graph' => ['view'],
                'Staff Present Today Widgtets' => ['view'],
                'Student Present Today Widgtets' => ['view'],
                'Student Head Count Widget' => ['view'],
                'Staff Approved Leave Widgtets' => ['view'],
                'Student Approved Leave Widgtets' => ['view'],
            ],
            'CBSE Examination' => [
                'CBSE Exam' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Schedule' => ['view'],
                'CBSE Exam Assign / View Student' => ['view', 'edit'],
                'CBSE Exam Subjects' => ['view', 'edit'],
                'CBSE Exam Marks' => ['view', 'edit'],
                'CBSE Exam Attendance' => ['view', 'edit'],
                'CBSE Exam Teacher Remark' => ['view', 'edit'],
                'CBSE Exam Print Marksheet' => ['view'],
                'CBSE Exam Grade' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Assign Observation' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Observation' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Observation Parameter' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Assessment' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Term' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Template' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Link Exam' => ['view'],
                'CBSE Exam Subject Marks Report' => ['view'],
                'CBSE Exam Template Marks Report' => ['view'],
                'CBSE Exam Setting' => ['view'],
                'CBSE Exam Generate Rank' => ['view'],
                'CBSE Exam Design Admit Card' => ['view', 'add', 'edit', 'delete'],
                'CBSE Exam Print Admit Card' => ['view'],
                'CBSE Exam Category' => ['view', 'add', 'edit', 'delete'],
            ],
            'Multi Branch' => [
                'Overview' => ['view'],
                'Daily Collection Report' => ['view'],
                'Payroll Report' => ['view'],
                'Income Report' => ['view'],
                'Expense Report' => ['view'],
                'User Log Report' => ['view'],
                'Setting' => ['view'],
                'Switch Branch' => ['view'],
            ],
            'Two Factor Authenticator' => [
                'Setting' => ['view'],
                'Setup 2FA' => ['view'],
            ],
            'QR Code Attendance' => [
                'Attendance' => ['view'],
                'Setting' => ['view'],
                'Terminal' => ['view'],
                'Face Registration' => ['view'],
                'Qr Code Generation' => ['view'],
                'Nfc Assignment' => ['view'],
                'Smart Attendance Settings' => ['view'],
            ],
            'Quick Fees' => [
                'Quick Fees' => ['view', 'add', 'delete'],
            ],
            'Thermal Print' => [
                'Thermal Print' => ['view'],
            ],
            'Whatsapp Messaging' => [
                'Whatsapp Messaging' => ['view'],
            ],
            'Lesson Plan' => [
                'Manage Lesson Plan' => ['view', 'add', 'edit', 'delete'],
                'Manage Syllabus Status' => ['view'],
                'Lesson' => ['view', 'add', 'edit', 'delete'],
                'Topic' => ['view', 'add', 'edit', 'delete'],
                'Comments' => ['view', 'add', 'edit', 'delete'],
                'Copy Old Lessons' => ['view'],
            ],
            'Online Examination' => [
                'Online Examination' => ['view', 'add', 'edit', 'delete'],
                'Question Bank' => ['view', 'add', 'edit', 'delete'],
                'Add Questions in Exam' => ['view', 'edit'],
                'Assign / View Student' => ['view', 'edit'],
                'Import Question' => ['view'],
            ],
            'Chat' => [
                'Chat' => ['view'],
            ],
            'Multi Class' => [
                'Multi Class Student' => ['view', 'add', 'edit', 'delete'],
            ],
            'Online Admission' => [
                'Online Admission' => ['view'],
            ],
            'Alumni' => [
                'Manage Alumni' => ['view', 'add', 'edit', 'delete'],
                'Events' => ['view', 'add', 'edit', 'delete'],
            ],
            'Annual Calendar' => [
                'Annual Calendar' => ['view', 'add', 'edit', 'delete'],
                'Holiday Type' => ['view', 'add', 'edit', 'delete'],
            ],
            'Student CV' => [
                'Download CV' => ['view'],
                'Build CV' => ['view', 'add', 'edit'],
                'Setting' => ['view'],
            ],
            'Zoom Live Classes' => [
                'Setting' => ['view', 'edit'],
                'Live Classes' => ['view', 'add', 'delete'],
                'Live Meeting' => ['view', 'add', 'delete'],
                'Live Meeting Report' => ['view'],
                'Live Classes Report' => ['view'],
            ],
            'Gmeet Live Classes' => [
                'Live Classes' => ['view', 'add', 'delete'],
                'Live Meeting' => ['view', 'add', 'delete'],
                'Live Meeting Report' => ['view'],
                'Live Classes Report' => ['view'],
                'Setting' => ['view', 'edit'],
            ],
            'Online Course' => [
                'Online Course' => ['view', 'add', 'edit', 'delete'],
                'Course Publish' => ['view', 'add', 'edit', 'delete'],
                'Course Section' => ['view', 'add', 'edit', 'delete'],
                'Course Lesson' => ['view', 'add', 'edit', 'delete'],
                'Course Quiz' => ['view', 'add', 'edit', 'delete'],
                'Offline Payment' => ['view', 'add', 'edit', 'delete'],
                'Student Course Purchase Report' => ['view'],
                'Course Sell Count Report' => ['view'],
                'Course Trending Report' => ['view'],
                'Course Complete Report' => ['view'],
                'Setting' => ['view', 'edit', 'delete'],
                'Course Rating Report' => ['view', 'delete'],
                'Guest Report' => ['view', 'edit', 'delete'],
                'Course Category' => ['view', 'add', 'edit', 'delete'],
                'Question Bank' => ['view', 'add', 'edit', 'delete'],
                'Question Tag' => ['view', 'add', 'edit', 'delete'],
                'Course Exam' => ['view', 'add', 'edit', 'delete'],
                'Course Assignment' => ['view', 'add', 'edit', 'delete'],
                'Course Add Questions in Exam' => ['view', 'add', 'edit'],
                'Course Evalute Assignment' => ['view', 'add', 'edit'],
                'Course Assignment Report' => ['view'],
                'Course Exam Result Report' => ['view'],
                'Course Exam Report' => ['view'],
                'Course Exam Attempt Report' => ['view'],
                'Course Certificate Template' => ['view', 'add', 'edit', 'delete'],
            ],
            'Behaviour Records' => [
                'Behaviour Records Assign Incident' => ['view', 'add', 'edit', 'delete'],
                'Behaviour Records Incident' => ['view', 'add', 'edit', 'delete'],
                'Student Incident Report' => ['view'],
                'Student Behaviour Rank Report' => ['view'],
                'Class Wise Rank Report' => ['view'],
                'Class Section Wise Rank Report' => ['view'],
                'House Wise Rank Report' => ['view'],
                'Incident Wise Report' => ['view'],
                'Behaviour Records Setting' => ['view', 'add', 'edit', 'delete'],
            ]
        ];

        $adminRole = \App\Models\Role::where('name', 'Admin')->first() ?? \App\Models\Role::find(2);

        foreach ($permissions as $module => $features) {
            foreach ($features as $feature => $capabilities) {
                foreach ($capabilities as $capability) {
                    $slug = \Illuminate\Support\Str::slug($module . '.' . $feature . '.' . $capability, '.');
                    $permission = \App\Models\Permission::firstOrCreate([
                        'name' => $slug,
                    ], [
                        'module' => $module,
                        'feature' => $feature,
                        'capability' => $capability,
                    ]);

                    // Tick columns accordingly (Assign to Admin role)
                    if ($adminRole) {
                        $adminRole->permissions()->syncWithoutDetaching([$permission->id]);
                    }
                }
            }
        }
    }
}
